# Generated by Django 2.2.12 on 2021-07-29 19:43

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddingFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=50.0, max_digits=19, verbose_name='Сумма')),
                ('purchase_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата покупки')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Успех пополнения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'пополнение',
                'verbose_name_plural': 'пополнения',
            },
        ),
    ]
